#!/bin/bash
#
# LANAgent Docker Setup
# Interactive setup wizard for Docker-based installation
#
# Usage:
#   ./scripts/setup/docker-setup.sh           # Interactive
#   ./scripts/setup/docker-setup.sh --quick   # Minimal (name + AI key only)
#

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
QUICK_MODE=false

if [ "$1" = "--quick" ]; then
    QUICK_MODE=true
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${BOLD}LANAgent Docker Setup${NC}                           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}  ${DIM}Autonomous Agent Framework${NC}                       ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# Check Docker
if ! command -v docker &>/dev/null; then
    echo -e "${RED}Docker is not installed.${NC}"
    echo "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
    echo -e "${RED}Docker Compose is not available.${NC}"
    echo "Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}Docker detected:${NC} $(docker --version | head -1)"
echo ""

# ─── Agent Name ───────────────────────────────────────────────────────
echo -e "${BOLD}1. Agent Name${NC}"
echo -e "${DIM}This is your agent's identity — visible on the P2P network and web UI.${NC}"
read -p "  Agent name [MyAgent]: " AGENT_NAME
AGENT_NAME=${AGENT_NAME:-MyAgent}
echo ""

# ─── AI Provider ──────────────────────────────────────────────────────
echo -e "${BOLD}2. AI Provider${NC}"
echo -e "${DIM}At least one AI provider key is required. Claude (Anthropic) recommended.${NC}"
echo ""
read -p "  Anthropic API Key (recommended): " ANTHROPIC_KEY
read -p "  OpenAI API Key (optional): " OPENAI_KEY

if [ -z "$ANTHROPIC_KEY" ] && [ -z "$OPENAI_KEY" ]; then
    echo -e "${RED}At least one AI provider key is required.${NC}"
    exit 1
fi
echo ""

# ─── Port ─────────────────────────────────────────────────────────────
AGENT_PORT=3000
if [ "$QUICK_MODE" = false ]; then
    echo -e "${BOLD}3. Web UI Port${NC}"
    read -p "  Port [3000]: " INPUT_PORT
    AGENT_PORT=${INPUT_PORT:-3000}
    echo ""
fi

# ─── Web Password ─────────────────────────────────────────────────────
WEB_PASSWORD="lanagent"
if [ "$QUICK_MODE" = false ]; then
    echo -e "${BOLD}4. Web UI Password${NC}"
    read -p "  Password [lanagent]: " INPUT_PASS
    WEB_PASSWORD=${INPUT_PASS:-lanagent}
    echo ""
fi

# ─── Owner Email ──────────────────────────────────────────────────────
OWNER_EMAIL=""
if [ "$QUICK_MODE" = false ]; then
    echo -e "${BOLD}5. Owner Email${NC}"
    echo -e "${DIM}Used for notifications and email verification.${NC}"
    read -p "  Email: " OWNER_EMAIL
    echo ""
fi

# ─── Telegram (optional) ─────────────────────────────────────────────
TELEGRAM_TOKEN=""
TELEGRAM_USER_ID=""
if [ "$QUICK_MODE" = false ]; then
    echo -e "${BOLD}6. Telegram Bot (optional)${NC}"
    echo -e "${DIM}Get a bot token from @BotFather on Telegram.${NC}"
    read -p "  Bot Token (Enter to skip): " TELEGRAM_TOKEN
    if [ -n "$TELEGRAM_TOKEN" ]; then
        read -p "  Your Telegram User ID: " TELEGRAM_USER_ID
    fi
    echo ""
fi

# ─── Generate Secrets ─────────────────────────────────────────────────
echo -e "${BLUE}Generating security keys...${NC}"
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)
ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)
echo -e "${GREEN}Done${NC}"
echo ""

# ─── Write .env ───────────────────────────────────────────────────────
echo -e "${BLUE}Writing .env file...${NC}"

cat > "$ENV_FILE" << EOF
# LANAgent Configuration
# Generated by docker-setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Agent Identity
AGENT_NAME=$AGENT_NAME
AGENT_PORT=$AGENT_PORT
AGENT_SSH_PORT=2222

# AI Providers
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
OPENAI_API_KEY=${OPENAI_KEY}
ANTHROPIC_ENABLE_WEB_SEARCH=true

# MongoDB (overridden by docker-compose to use container)
MONGODB_URI=mongodb://localhost:27017/$AGENT_NAME

# Owner
EMAIL_OF_MASTER=${OWNER_EMAIL}

# Security (auto-generated)
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
WEB_UI_PASSWORD=${WEB_PASSWORD}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_USER_ID=${TELEGRAM_USER_ID}

# P2P Network
P2P_ENABLED=true
P2P_DISPLAY_NAME=$AGENT_NAME

# Self-Modification (disabled by default for Docker)
# GIT_PERSONAL_ACCESS_TOKEN=
# GITHUB_REPO=
AGENT_REPO_PATH=.

# SSH Interface
SSH_USERNAME=lanagent
SSH_PASSWORD=changeme
EOF

echo -e "${GREEN}.env created${NC}"
echo ""

# ─── Create Directories ──────────────────────────────────────────────
mkdir -p "$PROJECT_DIR"/{data,data/agent,logs,workspace}

# ─── Git Setup (for auto-updates) ────────────────────────────────────
echo -e "${BLUE}Setting up auto-updates...${NC}"
cd "$PROJECT_DIR"
if [ ! -d ".git" ]; then
    git init -q
    git branch -m main 2>/dev/null
    git config --global --add safe.directory "$PROJECT_DIR" 2>/dev/null
fi
# Set upstream if not already set
if ! git remote | grep -q upstream; then
    git remote add upstream https://github.com/PortableDiag/LANAgent.git 2>/dev/null
fi
# Set origin to user's fork if they have one
if [ -n "$GITHUB_REPO" ] && ! git remote | grep -q origin; then
    git remote add origin "$GITHUB_REPO" 2>/dev/null
fi
echo -e "${GREEN}Auto-update configured${NC}"
echo ""

# ─── Auto-Update Cron (daily at 4 AM) ────────────────────────────────
CRON_CMD="cd $PROJECT_DIR && git pull upstream main --ff-only 2>/dev/null && docker compose up -d --build --quiet-pull 2>/dev/null"
if ! crontab -l 2>/dev/null | grep -q "lanagent.*docker compose"; then
    (crontab -l 2>/dev/null; echo "0 4 * * * $CRON_CMD # LANAgent auto-update") | crontab -
    echo -e "${GREEN}Auto-update scheduled (daily 4 AM)${NC}"
fi
echo ""

# ─── Build & Start ────────────────────────────────────────────────────
echo -e "${BOLD}Building and starting LANAgent...${NC}"
echo -e "${DIM}This may take a few minutes on first run (downloading dependencies).${NC}"
echo ""

docker compose up -d --build 2>&1 | tail -5

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${GREEN}${BOLD}LANAgent is starting!${NC}                           ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Agent:${NC}     $AGENT_NAME"
echo -e "  ${BOLD}Web UI:${NC}    http://localhost:$AGENT_PORT"
echo -e "  ${BOLD}Password:${NC}  $WEB_PASSWORD"
echo -e "  ${BOLD}SSH:${NC}       ssh lanagent@localhost -p 2222"
echo ""
echo -e "  ${DIM}The web UI takes about 3 minutes to fully start.${NC}"
echo -e "  ${DIM}Check status: docker compose ps${NC}"
echo -e "  ${DIM}View logs:    docker compose logs -f lanagent${NC}"
echo -e "  ${DIM}Stop:         docker compose down${NC}"
echo -e "  ${DIM}Update:       git pull && docker compose up -d --build${NC}"
echo ""
echo -e "  ${BOLD}Configure plugins:${NC} Settings > Plugins in the web UI"
echo -e "  ${BOLD}Welcome package:${NC}  Your email and 200 SKYNET tokens will be provisioned automatically (~1 hour after connecting to the network)."
echo -e "  ${BOLD}Edit config:${NC}        nano .env && docker compose restart lanagent"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
