import { BasePlugin } from '../core/basePlugin.js';
import axios from 'axios';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import crypto from 'crypto';

export default class AIDetectorPlugin extends BasePlugin {
  constructor(agent) {
    super(agent);
    this.name = 'aiDetector';
    this.version = '1.0.0';
    this.description = 'Detect AI-generated content — text, images, video, and audio';
    this.serviceUrl = process.env.DETECTOR_URL || 'http://127.0.0.1:5100';
    this.commands = [
      {
        command: 'detectText',
        description: 'Analyze text to determine if it was AI-generated',
        usage: 'detectText [text or paste content]',
        offerAsService: true
      },
      {
        command: 'detectImage',
        description: 'Analyze an image to determine if it was AI-generated',
        usage: 'detectImage [url or file path]',
        offerAsService: true
      },
      {
        command: 'detectVideo',
        description: 'Analyze a video for AI-generated frames',
        usage: 'detectVideo [url or file path]',
        offerAsService: true
      },
      {
        command: 'detectAudio',
        description: 'Analyze audio to detect AI-generated speech',
        usage: 'detectAudio [url or file path]',
        offerAsService: true
      },
      {
        command: 'detect',
        description: 'Auto-detect content type and analyze for AI generation',
        usage: 'detect [text, url, or file path]',
        offerAsService: true
      },
      {
        command: 'status',
        description: 'Check AI detector service health and loaded models',
        usage: 'status'
      }
    ];
  }

  async execute(params) {
    let action, data;
    if (typeof params === 'string') {
      action = params;
      data = arguments[1] || {};
    } else {
      ({ action, ...data } = params);
    }

    try {
      switch (action) {
        case 'detectText':
          return await this.detectText(data);
        case 'detectImage':
          return await this.detectImage(data);
        case 'detectVideo':
          return await this.detectVideo(data);
        case 'detectAudio':
          return await this.detectAudio(data);
        case 'detect':
          return await this.autoDetect(data);
        case 'status':
          return await this.getStatus();
        default:
          return { success: false, error: 'Unknown action. Use: detectText, detectImage, detectVideo, detectAudio, detect, status' };
      }
    } catch (error) {
      this.logger.error(`AI Detector error (${action}):`, error.message);
      if (error.code === 'ECONNREFUSED') {
        return {
          success: false,
          error: 'AI Detector service is not running. Start it with: pm2 start ecosystem.config.cjs'
        };
      }
      return { success: false, error: error.message };
    }
  }

  async getStatus() {
    try {
      const response = await axios.get(`${this.serviceUrl}/health`, { timeout: 5000 });
      return { success: true, ...response.data };
    } catch (error) {
      if (error.code === 'ECONNREFUSED') {
        return { success: false, status: 'offline', error: 'Detector service not running' };
      }
      return { success: false, error: error.message };
    }
  }

  async detectText(data) {
    const text = data.text || data.content || data.query || '';
    if (!text.trim()) {
      return { success: false, error: 'No text provided. Pass text in the "text" field.' };
    }
    if (text.trim().length < 50) {
      return { success: false, error: 'Text too short. Need at least 50 characters for reliable detection.' };
    }

    const start = Date.now();
    const prompt = `You are an AI-generated text detector. Analyze the following text and determine whether it was written by a human or generated by an AI language model (ChatGPT, Claude, Gemini, etc.).

Consider these signals:
- Vocabulary diversity and word choice patterns
- Sentence structure variety (humans vary more, AI is uniform)
- Presence of filler words, slang, typos, or informal language (suggests human)
- Overly polished, formal, or generic phrasing (suggests AI)
- Repetitive sentence starters or parallel structures (suggests AI)
- Personal anecdotes, specific details, or emotional nuance (suggests human)
- Hedging phrases like "It's important to note" or "In conclusion" (suggests AI)

TEXT TO ANALYZE:
"""
${text.trim().substring(0, 2000)}
"""

Respond with ONLY a JSON object in this exact format:
{"verdict": "ai_generated" or "human" or "uncertain", "confidence": 0.0-1.0, "reasoning": "brief explanation of key signals detected"}`;

    try {
      const response = await this.agent.providerManager.generateResponse(prompt, {
        maxTokens: 300,
        temperature: 0.1,
        enableWebSearch: false
      });

      const content = response?.content || '';
      // Extract JSON from response
      const cleaned = content.replace(/```\w*\n?/g, '');
      const firstBrace = cleaned.indexOf('{');
      const lastBrace = cleaned.lastIndexOf('}');

      if (firstBrace === -1 || lastBrace <= firstBrace) {
        return { success: false, error: 'AI provider returned invalid response' };
      }

      let jsonStr = cleaned.substring(firstBrace, lastBrace + 1);
      const parsed = JSON.parse(jsonStr);

      return {
        success: true,
        type: 'text',
        verdict: parsed.verdict || 'uncertain',
        confidence: Math.round((parsed.confidence || 0.5) * 1000) / 1000,
        score: parsed.confidence || 0.5,
        reasoning: parsed.reasoning || 'No reasoning provided',
        processing_time_ms: Date.now() - start
      };
    } catch (error) {
      this.logger.error('Text detection via LLM failed:', error.message);
      return { success: false, error: `Text analysis failed: ${error.message}` };
    }
  }

  async detectImage(data) {
    const fileBuffer = await this._resolveFileInput(data);
    if (!fileBuffer) {
      return { success: false, error: 'No image provided. Pass a URL, file path, base64, or buffer.' };
    }

    const FormData = (await import('form-data')).default;
    const form = new FormData();
    form.append('file', fileBuffer, { filename: data.filename || 'image.jpg' });

    const response = await axios.post(`${this.serviceUrl}/detect/image`, form, {
      headers: form.getHeaders(),
      timeout: 60000
    });

    return this._formatResult('image', response.data);
  }

  async detectAudio(data) {
    const fileBuffer = await this._resolveFileInput(data);
    if (!fileBuffer) {
      return { success: false, error: 'No audio provided. Pass a URL, file path, base64, or buffer.' };
    }

    // Step 1: transcribe via Python service
    const FormData = (await import('form-data')).default;
    const form = new FormData();
    form.append('file', fileBuffer, { filename: data.filename || 'audio.wav' });

    const transcribeResponse = await axios.post(`${this.serviceUrl}/detect/audio`, form, {
      headers: form.getHeaders(),
      timeout: 120000
    });

    if (!transcribeResponse.data.success) {
      return this._formatResult('audio', transcribeResponse.data);
    }

    const transcript = transcribeResponse.data.result?.transcript || '';
    if (!transcript || transcript.length < 20) {
      return {
        success: true,
        type: 'audio',
        verdict: 'insufficient_data',
        confidence: 0,
        transcript,
        reasoning: 'Audio transcript too short for reliable analysis.'
      };
    }

    // Step 2: analyze transcript via LLM
    const textResult = await this.detectText({ text: transcript });
    if (textResult.success) {
      textResult.type = 'audio';
      textResult.transcript = transcript;
      textResult.reasoning = `Audio transcribed (${transcript.length} chars), then analyzed: ${textResult.reasoning}`;
    }
    return textResult;
  }

  async detectVideo(data) {
    const filePath = await this._resolveToFilePath(data);
    if (!filePath) {
      return { success: false, error: 'No video provided. Pass a URL or file path.' };
    }

    // Extract frames using FFmpeg
    const framesDir = path.join(os.tmpdir(), `aidetect_${crypto.randomBytes(8).toString('hex')}`);
    await fs.mkdir(framesDir, { recursive: true });

    try {
      const ffmpegPlugin = this.agent.apiManager?.getPlugin('ffmpeg');
      let framePaths = [];

      if (ffmpegPlugin) {
        // Use existing FFmpeg plugin
        try {
          await ffmpegPlugin.execute({
            action: 'extract',
            input: filePath,
            outputDir: framesDir,
            type: 'frames',
            options: { fps: 0.5 }
          });
          const files = await fs.readdir(framesDir);
          framePaths = files
            .filter(f => f.endsWith('.png') || f.endsWith('.jpg'))
            .sort()
            .slice(0, 20)
            .map(f => path.join(framesDir, f));
        } catch (ffmpegErr) {
          this.logger.warn(`FFmpeg plugin failed, trying direct command: ${ffmpegErr.message}`);
        }
      }

      // Fallback: direct ffmpeg command
      if (framePaths.length === 0) {
        const { exec } = await import('child_process');
        const { promisify } = await import('util');
        const execAsync = promisify(exec);
        await execAsync(`ffmpeg -i "${filePath}" -vf "fps=0.5" -frames:v 20 "${framesDir}/frame_%04d.png" -y`, {
          timeout: 60000
        });
        const files = await fs.readdir(framesDir);
        framePaths = files
          .filter(f => f.endsWith('.png'))
          .sort()
          .slice(0, 20)
          .map(f => path.join(framesDir, f));
      }

      if (framePaths.length === 0) {
        return { success: false, error: 'Could not extract frames from video. Is ffmpeg installed?' };
      }

      // Analyze each frame
      const frameResults = [];
      for (const framePath of framePaths) {
        try {
          const frameBuffer = await fs.readFile(framePath);
          const FormData = (await import('form-data')).default;
          const form = new FormData();
          form.append('file', frameBuffer, { filename: path.basename(framePath) });

          const response = await axios.post(`${this.serviceUrl}/detect/image`, form, {
            headers: form.getHeaders(),
            timeout: 30000
          });

          if (response.data.success) {
            frameResults.push(response.data.result);
          }
        } catch (frameErr) {
          this.logger.warn(`Frame analysis failed for ${path.basename(framePath)}: ${frameErr.message}`);
        }
      }

      if (frameResults.length === 0) {
        return { success: false, error: 'Could not analyze any video frames.' };
      }

      // Aggregate results via majority vote
      const aiCount = frameResults.filter(r => r.verdict === 'ai_generated').length;
      const humanCount = frameResults.filter(r => r.verdict === 'human').length;
      const avgConfidence = frameResults.reduce((sum, r) => sum + (r.confidence || 0), 0) / frameResults.length;
      const avgScore = frameResults.reduce((sum, r) => sum + (r.score || 0), 0) / frameResults.length;

      let verdict;
      if (aiCount > frameResults.length / 2) verdict = 'ai_generated';
      else if (humanCount > frameResults.length / 2) verdict = 'human';
      else verdict = 'uncertain';

      return {
        success: true,
        type: 'video',
        verdict,
        confidence: round3(avgConfidence),
        score: round4(avgScore),
        reasoning: `Analyzed ${frameResults.length} frames from video. ${aiCount} frames detected as AI-generated, ${humanCount} as human, ${frameResults.length - aiCount - humanCount} uncertain.`,
        details: {
          framesAnalyzed: frameResults.length,
          framesAI: aiCount,
          framesHuman: humanCount,
          framesUncertain: frameResults.length - aiCount - humanCount,
          perFrameResults: frameResults
        }
      };

    } finally {
      // Cleanup temp frames
      try {
        const files = await fs.readdir(framesDir);
        for (const f of files) await fs.unlink(path.join(framesDir, f));
        await fs.rmdir(framesDir);
      } catch (cleanErr) {
        this.logger.debug(`Cleanup failed for ${framesDir}: ${cleanErr.message}`);
      }
      // Cleanup temp video file if we created one
      if (data._tempPath) {
        try { await fs.unlink(data._tempPath); } catch {}
      }
    }
  }

  async autoDetect(data) {
    const input = data.text || data.content || data.url || data.path || data.query || '';

    // Check if it's a URL to a file
    if (typeof input === 'string' && /^https?:\/\//i.test(input)) {
      const ext = input.split('?')[0].split('.').pop().toLowerCase();
      if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff'].includes(ext)) {
        return await this.detectImage({ url: input, filename: `image.${ext}` });
      }
      if (['mp4', 'avi', 'mov', 'mkv', 'webm', 'flv'].includes(ext)) {
        return await this.detectVideo({ url: input });
      }
      if (['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'wma'].includes(ext)) {
        return await this.detectAudio({ url: input, filename: `audio.${ext}` });
      }
      // Default URL to text content fetch
      return await this.detectText({ text: input });
    }

    // Check if it's a file path
    if (typeof input === 'string' && !input.includes('\n') && input.length < 500) {
      try {
        await fs.access(input);
        const ext = path.extname(input).toLowerCase().slice(1);
        if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff'].includes(ext)) {
          return await this.detectImage({ path: input, filename: path.basename(input) });
        }
        if (['mp4', 'avi', 'mov', 'mkv', 'webm', 'flv'].includes(ext)) {
          return await this.detectVideo({ path: input });
        }
        if (['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'wma'].includes(ext)) {
          return await this.detectAudio({ path: input, filename: path.basename(input) });
        }
      } catch {
        // Not a file, treat as text
      }
    }

    // Check for buffer/base64 with content type hint
    if (data.buffer || data.base64) {
      const mimeType = data.mimeType || data.mime || '';
      if (mimeType.startsWith('image/')) return await this.detectImage(data);
      if (mimeType.startsWith('video/')) return await this.detectVideo(data);
      if (mimeType.startsWith('audio/')) return await this.detectAudio(data);
      // Default to image for raw buffers
      return await this.detectImage(data);
    }

    // Default: treat as text
    return await this.detectText({ text: input });
  }

  // --- Helpers ---

  async _resolveFileInput(data) {
    // From buffer
    if (data.buffer) {
      return Buffer.isBuffer(data.buffer) ? data.buffer : Buffer.from(data.buffer);
    }
    // From base64
    if (data.base64) {
      return Buffer.from(data.base64, 'base64');
    }
    // From file path
    if (data.path) {
      return await fs.readFile(data.path);
    }
    // From URL
    if (data.url) {
      const response = await axios.get(data.url, {
        responseType: 'arraybuffer',
        timeout: 30000,
        maxContentLength: 100 * 1024 * 1024 // 100MB max
      });
      return Buffer.from(response.data);
    }
    return null;
  }

  async _resolveToFilePath(data) {
    // Already a path
    if (data.path) {
      try {
        await fs.access(data.path);
        return data.path;
      } catch {
        return null;
      }
    }
    // From URL — download to temp file
    if (data.url) {
      const ext = data.url.split('?')[0].split('.').pop().toLowerCase() || 'mp4';
      const tmpPath = path.join(os.tmpdir(), `aidetect_${crypto.randomBytes(8).toString('hex')}.${ext}`);
      const response = await axios.get(data.url, {
        responseType: 'arraybuffer',
        timeout: 120000,
        maxContentLength: 500 * 1024 * 1024 // 500MB max for video
      });
      await fs.writeFile(tmpPath, Buffer.from(response.data));
      data._tempPath = tmpPath;
      return tmpPath;
    }
    // From buffer — write to temp file
    if (data.buffer || data.base64) {
      const buf = data.buffer
        ? (Buffer.isBuffer(data.buffer) ? data.buffer : Buffer.from(data.buffer))
        : Buffer.from(data.base64, 'base64');
      const tmpPath = path.join(os.tmpdir(), `aidetect_${crypto.randomBytes(8).toString('hex')}.mp4`);
      await fs.writeFile(tmpPath, buf);
      data._tempPath = tmpPath;
      return tmpPath;
    }
    return null;
  }

  _formatResult(type, responseData) {
    if (!responseData.success) {
      return { success: false, error: responseData.detail || 'Detection failed' };
    }
    return {
      success: true,
      type,
      ...responseData.result
    };
  }
}

function round3(n) { return Math.round(n * 1000) / 1000; }
function round4(n) { return Math.round(n * 10000) / 10000; }
