import { FeatureRequest } from '../../models/FeatureRequest.js';
import { SystemSettings } from '../../models/SystemSettings.js';
import { authenticateToken } from './auth.js';
import { logger } from '../../utils/logger.js';

const AUTO_APPROVE_SETTING_KEY = 'featureRequests.autoApprove';

/**
 * Setup feature request API routes
 * 
 * @param {import('express').Application} app - Express application
 * @param {import('../../core/agent.js').Agent} agent - LANAgent instance
 */
export function setupFeatureRequestRoutes(app, agent) {

  // Get all feature requests with optional filtering
  app.get('/api/feature-requests', authenticateToken, async (req, res) => {
    try {
      const { 
        status, 
        category, 
        priority, 
        autoGenerated,
        limit = 50,
        offset = 0
      } = req.query;

      let query = {};
      
      if (status && status !== 'all') {
        if (status === 'pending') {
          // Show submitted and auto-approved (planned) items that need review
          query.status = { $in: ['submitted', 'planned', 'analyzing'] };
        } else {
          query.status = status;
        }
      }
      
      if (category && category !== 'all') {
        query.category = category;
      }
      
      if (priority && priority !== 'all') {
        query.priority = priority;
      }
      
      if (autoGenerated !== undefined) {
        query.autoGenerated = autoGenerated === 'true';
      }

      const requests = await FeatureRequest.find(query)
        .sort({ priority: -1, submittedAt: -1 })
        .limit(parseInt(limit))
        .skip(parseInt(offset));

      const total = await FeatureRequest.countDocuments(query);

      res.json({
        success: true,
        data: {
          requests,
          pagination: {
            total,
            limit: parseInt(limit),
            offset: parseInt(offset),
            hasMore: total > parseInt(offset) + parseInt(limit)
          }
        }
      });

    } catch (error) {
      logger.error('Failed to get feature requests:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to retrieve feature requests'
      });
    }
  });

  // Get a specific feature request
  app.get('/api/feature-requests/:id', authenticateToken, async (req, res) => {
    try {
      const request = await FeatureRequest.findById(req.params.id);
      
      if (!request) {
        return res.status(404).json({
          success: false,
          error: 'Feature request not found'
        });
      }

      res.json({
        success: true,
        data: request
      });

    } catch (error) {
      logger.error('Failed to get feature request:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to retrieve feature request'
      });
    }
  });

  // Submit a new feature request
  app.post('/api/feature-requests', authenticateToken, async (req, res) => {
    try {
      const {
        title,
        description,
        category,
        priority,
        useCase,
        implementation,
        relatedPlugin
      } = req.body;

      // Validate required fields
      if (!title || !description || !category || !priority) {
        return res.status(400).json({
          success: false,
          error: 'Missing required fields: title, description, category, priority'
        });
      }

      // Check if auto-approve is enabled
      const autoApproveEnabled = await SystemSettings.getSetting(AUTO_APPROVE_SETTING_KEY, false);

      const featureRequest = new FeatureRequest({
        title: title.trim(),
        description: description.trim(),
        category,
        priority,
        useCase: useCase?.trim(),
        implementation: implementation?.trim(),
        relatedPlugin,
        submittedBy: req.user?.userId || 'web-user',
        status: autoApproveEnabled ? 'planned' : 'submitted',
        notes: autoApproveEnabled ? 'Auto-approved' : undefined
      });

      await featureRequest.save();

      // Log the submission
      logger.info('New feature request submitted:', {
        id: featureRequest._id,
        title: featureRequest.title,
        category: featureRequest.category,
        priority: featureRequest.priority
      });

      // Optionally trigger analysis if self-modification is enabled
      if (agent.selfModification?.enabled) {
        try {
          // Add to upgrade plans for analysis
          const upgradePlanItem = await featureRequest.addToUpgradePlan();
          logger.info('Feature request added to upgrade plans for analysis');
        } catch (error) {
          logger.warn('Failed to add feature request to upgrade plans:', error);
        }
      }

      res.json({
        success: true,
        data: featureRequest,
        message: 'Feature request submitted successfully'
      });

    } catch (error) {
      logger.error('Failed to submit feature request:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to submit feature request'
      });
    }
  });

  // Update feature request status
  app.put('/api/feature-requests/:id/status', authenticateToken, async (req, res) => {
    try {
      const { status, notes } = req.body;

      if (!status) {
        return res.status(400).json({
          success: false,
          error: 'Status is required'
        });
      }

      const request = await FeatureRequest.findById(req.params.id);
      
      if (!request) {
        return res.status(404).json({
          success: false,
          error: 'Feature request not found'
        });
      }

      const oldStatus = request.status;
      await request.updateStatus(status, notes);

      logger.info('Feature request status updated:', {
        id: request._id,
        title: request.title,
        oldStatus: oldStatus,
        newStatus: status
      });

      res.json({
        success: true,
        data: request,
        message: 'Feature request status updated'
      });

    } catch (error) {
      logger.error('Failed to update feature request status:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to update feature request status'
      });
    }
  });

  // Delete a feature request
  app.delete('/api/feature-requests/:id', authenticateToken, async (req, res) => {
    try {
      const request = await FeatureRequest.findById(req.params.id);
      
      if (!request) {
        return res.status(404).json({
          success: false,
          error: 'Feature request not found'
        });
      }

      await FeatureRequest.findByIdAndDelete(req.params.id);

      logger.info('Feature request deleted:', {
        id: req.params.id,
        title: request.title
      });

      res.json({
        success: true,
        message: 'Feature request deleted successfully'
      });

    } catch (error) {
      logger.error('Failed to delete feature request:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to delete feature request'
      });
    }
  });

  // Vote on a feature request
  app.post('/api/feature-requests/:id/vote', authenticateToken, async (req, res) => {
    try {
      const { direction } = req.body; // 'up' or 'down'

      const request = await FeatureRequest.findById(req.params.id);
      
      if (!request) {
        return res.status(404).json({
          success: false,
          error: 'Feature request not found'
        });
      }

      if (direction === 'up') {
        request.votes += 1;
      } else if (direction === 'down') {
        request.votes -= 1;
      } else {
        return res.status(400).json({
          success: false,
          error: 'Invalid vote direction. Use "up" or "down"'
        });
      }

      await request.save();

      res.json({
        success: true,
        data: { votes: request.votes },
        message: 'Vote recorded successfully'
      });

    } catch (error) {
      logger.error('Failed to vote on feature request:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to vote on feature request'
      });
    }
  });

  // Trigger analysis of pending feature requests
  app.post('/api/feature-requests/analyze', authenticateToken, async (req, res) => {
    try {
      if (!agent.selfModification?.enabled) {
        return res.status(400).json({
          success: false,
          error: 'Self-modification service is not enabled'
        });
      }

      // Get pending requests
      const pendingRequests = await FeatureRequest.getByStatus('submitted');

      let analyzed = 0;
      for (const request of pendingRequests) {
        try {
          await request.updateStatus('analyzing', 'Automated analysis started');
          analyzed++;
        } catch (error) {
          logger.warn(`Failed to start analysis for request ${request._id}:`, error);
        }
      }

      // Trigger self-modification analysis
      try {
        await agent.selfModification.checkForImprovements();
        logger.info('Self-modification analysis triggered for feature requests');
      } catch (error) {
        logger.warn('Failed to trigger self-modification analysis:', error);
      }

      res.json({
        success: true,
        data: { analyzed },
        message: `Analysis started for ${analyzed} pending feature requests`
      });

    } catch (error) {
      logger.error('Failed to trigger feature request analysis:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to trigger feature request analysis'
      });
    }
  });

  // Get statistics about feature requests
  app.get('/api/feature-requests/stats', authenticateToken, async (req, res) => {
    try {
      const stats = {
        total: await FeatureRequest.countDocuments(),
        byStatus: {},
        byCategory: {},
        byPriority: {},
        userSubmitted: await FeatureRequest.countDocuments({ autoGenerated: false }),
        autoGenerated: await FeatureRequest.countDocuments({ autoGenerated: true }),
        recentSubmissions: await FeatureRequest.countDocuments({
          submittedAt: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) }
        })
      };

      // Get counts by status
      const statusCounts = await FeatureRequest.aggregate([
        { $group: { _id: '$status', count: { $sum: 1 } } }
      ]);
      statusCounts.forEach(item => {
        stats.byStatus[item._id] = item.count;
      });

      // Get counts by category
      const categoryCounts = await FeatureRequest.aggregate([
        { $group: { _id: '$category', count: { $sum: 1 } } }
      ]);
      categoryCounts.forEach(item => {
        stats.byCategory[item._id] = item.count;
      });

      // Get counts by priority
      const priorityCounts = await FeatureRequest.aggregate([
        { $group: { _id: '$priority', count: { $sum: 1 } } }
      ]);
      priorityCounts.forEach(item => {
        stats.byPriority[item._id] = item.count;
      });

      res.json({
        success: true,
        data: stats
      });

    } catch (error) {
      logger.error('Failed to get feature request stats:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to retrieve feature request statistics'
      });
    }
  });

  // Clear auto-generated feature requests (for resetting planned upgrades)
  app.delete('/api/feature-requests/auto-generated', authenticateToken, async (req, res) => {
    try {
      const result = await FeatureRequest.deleteMany({ autoGenerated: true });
      
      logger.info('Cleared auto-generated feature requests:', {
        deletedCount: result.deletedCount
      });

      res.json({
        success: true,
        data: { deletedCount: result.deletedCount },
        message: `Cleared ${result.deletedCount} auto-generated feature requests`
      });

    } catch (error) {
      logger.error('Failed to clear auto-generated feature requests:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to clear auto-generated feature requests'
      });
    }
  });

  // Deduplicate feature requests
  app.post('/api/feature-requests/deduplicate', authenticateToken, async (req, res) => {
    try {
      // Find duplicates by title
      const duplicates = await FeatureRequest.aggregate([
        { $group: { 
          _id: '$title', 
          count: { $sum: 1 }, 
          ids: { $push: '$_id' },
          priorities: { $push: '$priority' },
          dates: { $push: '$submittedAt' },
          votes: { $push: '$votes' }
        }},
        { $match: { count: { $gt: 1 } } }
      ]);
      
      let totalDeleted = 0;
      
      for (const dup of duplicates) {
        // Sort by priority (keep highest), then by votes, then by date (keep oldest)
        const priorityOrder = { critical: 4, high: 3, medium: 2, low: 1 };
        const sorted = dup.ids.map((id, index) => ({
          id,
          priority: priorityOrder[dup.priorities[index]] || 0,
          votes: dup.votes[index] || 0,
          date: dup.dates[index]
        })).sort((a, b) => {
          // First by priority (highest first)
          if (b.priority !== a.priority) return b.priority - a.priority;
          // Then by votes (most first)
          if (b.votes !== a.votes) return b.votes - a.votes;
          // Then by date (oldest first)
          return new Date(a.date) - new Date(b.date);
        });
        
        // Keep the first one, delete the rest
        const toDelete = sorted.slice(1).map(item => item.id);
        if (toDelete.length > 0) {
          await FeatureRequest.deleteMany({ _id: { $in: toDelete } });
          totalDeleted += toDelete.length;
          logger.info(`Deleted ${toDelete.length} duplicates for "${dup._id}"`);
        }
      }
      
      res.json({
        success: true,
        data: {
          duplicateGroups: duplicates.length,
          deletedCount: totalDeleted
        },
        message: `Deduplicated feature requests: removed ${totalDeleted} duplicates from ${duplicates.length} groups`
      });

    } catch (error) {
      logger.error('Failed to deduplicate feature requests:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to deduplicate feature requests'
      });
    }
  });

  // Get auto-approve setting
  app.get('/api/feature-requests/settings/auto-approve', authenticateToken, async (req, res) => {
    try {
      const enabled = await SystemSettings.getSetting(AUTO_APPROVE_SETTING_KEY, false);
      res.json({
        success: true,
        data: { enabled }
      });
    } catch (error) {
      logger.error('Failed to get auto-approve setting:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to get auto-approve setting'
      });
    }
  });

  // Set auto-approve setting
  app.put('/api/feature-requests/settings/auto-approve', authenticateToken, async (req, res) => {
    try {
      const { enabled } = req.body;

      if (typeof enabled !== 'boolean') {
        return res.status(400).json({
          success: false,
          error: 'enabled must be a boolean'
        });
      }

      await SystemSettings.setSetting(
        AUTO_APPROVE_SETTING_KEY,
        enabled,
        'Auto-approve all new feature requests',
        'feature-requests'
      );

      logger.info(`Feature request auto-approve ${enabled ? 'enabled' : 'disabled'}`);

      // If enabling, also approve all pending requests
      if (enabled) {
        const result = await FeatureRequest.updateMany(
          { status: 'submitted' },
          { status: 'planned', notes: 'Auto-approved (bulk)' }
        );

        logger.info(`Auto-approved ${result.modifiedCount} pending feature requests`);

        res.json({
          success: true,
          data: { enabled, approvedCount: result.modifiedCount },
          message: `Auto-approve enabled. ${result.modifiedCount} pending requests approved.`
        });
      } else {
        res.json({
          success: true,
          data: { enabled },
          message: 'Auto-approve disabled'
        });
      }
    } catch (error) {
      logger.error('Failed to set auto-approve setting:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to set auto-approve setting'
      });
    }
  });
}