import mongoose from 'mongoose';
import NodeCache from 'node-cache';
import { retryOperation } from '../utils/retryUtils.js';
import { logger } from '../utils/logger.js';
import crypto from 'node:crypto';

/**
 * Feature Request Schema for user-submitted feature requests and improvements
 */
const FeatureRequestSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
    maxLength: 200
  },
  
  description: {
    type: String,
    required: true,
    trim: true,
    maxLength: 2000
  },
  
  category: {
    type: String,
    required: true,
    enum: [
      'core',
      'plugin', 
      'plugin-new',
      'ui',
      'api',
      'performance',
      'security',
      'integration',
      'automation',
      'other'
    ]
  },
  
  // Deterministic content fingerprint for idempotent creates + dup detection.
  // Sparse so legacy docs without this field aren't penalized.
  contentFingerprint: {
    type: String,
    index: true,
    unique: true,
    sparse: true
  },

  priority: {
    type: String,
    required: true,
    enum: ['critical', 'high', 'medium', 'low']
  },
  
  status: {
    type: String,
    default: 'submitted',
    enum: [
      'submitted',
      'analyzing', 
      'planned',
      'in-progress',
      'completed',
      'rejected'
    ]
  },
  
  useCase: {
    type: String,
    maxLength: 1000
  },
  
  implementation: {
    type: String,
    maxLength: 1000
  },
  
  relatedPlugin: {
    type: String,
    enum: [
      'tasks', 'email', 'git', 'websearch', 'system', 'development',
      'software', 'scraper', 'monitoring', 'network', 'vpn', 'firewall',
      'ssh', 'samba', 'docker', 'ffmpeg', 'ytdlp', 'projects',
      'bugDetector', 'devenv', 'virustotal', 'backupStrategy',
      'documentIntelligence'
    ]
  },
  
  submittedBy: {
    type: String,
    default: 'user'
  },
  
  submittedAt: {
    type: Date,
    default: Date.now
  },
  
  analyzedAt: {
    type: Date
  },
  
  completedAt: {
    type: Date
  },
  
  estimatedEffort: {
    type: String,
    enum: ['low', 'medium', 'high', 'very-high']
  },
  
  benefits: [{
    type: String,
    maxLength: 200
  }],
  
  notes: {
    type: String,
    maxLength: 1000
  },
  
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  implementationFile: {
    type: String
  },
  
  relatedPullRequest: {
    type: String
  },
  
  votes: {
    type: Number,
    default: 0
  },
  
  // GitHub discovery references
  githubReferences: [{
    repository: String,
    url: String,
    filePath: String,
    codeSnippet: {
      type: String,
      maxLength: 5000
    },
    language: String,
    extractedAt: {
      type: Date,
      default: Date.now
    },
    contextNotes: String
  }],
  
  // Store relevant documentation/examples
  implementationExamples: [{
    source: String,
    description: String,
    code: {
      type: String,
      maxLength: 10000
    },
    language: String
  }],

  // New field to track the lifecycle of feature requests
  statusHistory: [{
    status: String,
    timestamp: {
      type: Date,
      default: Date.now
    },
    notes: String
  }]
}, {
  timestamps: true,
  collection: 'featureRequests'
});

// Indexes for efficient querying
FeatureRequestSchema.index({ status: 1, priority: -1 });
FeatureRequestSchema.index({ category: 1, submittedAt: -1 });
FeatureRequestSchema.index({ submittedAt: -1 });
FeatureRequestSchema.index({ autoGenerated: 1 });

// Caching setup
const featureRequestCache = new NodeCache({ stdTTL: 300, checkperiod: 60 });

// Methods
FeatureRequestSchema.methods.updateStatus = function(newStatus, notes = '') {
  this.status = newStatus;
  if (notes) this.notes = notes;
  
  // Log the status change in the history
  this.statusHistory.push({
    status: newStatus,
    notes: notes
  });

  if (newStatus === 'analyzing') {
    this.analyzedAt = new Date();
  } else if (newStatus === 'completed') {
    this.completedAt = new Date();
  }
  
  return this.save();
};

FeatureRequestSchema.methods.addToUpgradePlan = async function() {
  // Convert feature request to upgrade plan format
  const upgradePlanItem = {
    id: `feature-${this._id}`,
    title: this.title,
    description: this.description,
    priority: this.priority.charAt(0).toUpperCase() + this.priority.slice(1),
    estimatedEffort: this.estimatedEffort || 'Medium',
    benefits: this.benefits.length > 0 ? this.benefits : ['User-requested feature'],
    status: 'Planned',
    file: this.implementationFile || 'TBD',
    type: 'feature-request',
    autoGenerated: false,
    category: this.category,
    relatedPlugin: this.relatedPlugin,
    featureRequestId: this._id
  };
  
  return upgradePlanItem;
};

// Static methods
FeatureRequestSchema.statics.getByStatus = function(status) {
  const cacheKey = `getByStatus-${status}`;
  const cachedData = featureRequestCache.get(cacheKey);
  if (cachedData) return Promise.resolve(cachedData);
  return retryOperation(() => this.find({ status }).sort({ priority: -1, submittedAt: -1 }))
    .then(data => { featureRequestCache.set(cacheKey, data); return data; })
    .catch(err => {
      logger.error(`Error fetching feature requests by status: ${err.message}`);
      throw err;
    });
};

FeatureRequestSchema.statics.getByCategory = function(category) {
  const cacheKey = `getByCategory-${category}`;
  const cachedData = featureRequestCache.get(cacheKey);
  if (cachedData) return Promise.resolve(cachedData);
  return retryOperation(() => this.find({ category }).sort({ priority: -1, submittedAt: -1 }))
    .then(data => { featureRequestCache.set(cacheKey, data); return data; })
    .catch(err => {
      logger.error(`Error fetching feature requests by category: ${err.message}`);
      throw err;
    });
};

FeatureRequestSchema.statics.getByPriority = function(priority) {
  const cacheKey = `getByPriority-${priority}`;
  const cachedData = featureRequestCache.get(cacheKey);
  if (cachedData) return Promise.resolve(cachedData);
  return retryOperation(() => this.find({ priority }).sort({ submittedAt: -1 }))
    .then(data => { featureRequestCache.set(cacheKey, data); return data; })
    .catch(err => {
      logger.error(`Error fetching feature requests by priority: ${err.message}`);
      throw err;
    });
};

FeatureRequestSchema.statics.getUserSubmitted = function() {
  const cacheKey = 'getUserSubmitted';
  const cachedData = featureRequestCache.get(cacheKey);
  if (cachedData) return Promise.resolve(cachedData);
  return retryOperation(() => this.find({ autoGenerated: false }).sort({ submittedAt: -1 }))
    .then(data => { featureRequestCache.set(cacheKey, data); return data; })
    .catch(err => {
      logger.error(`Error fetching user-submitted feature requests: ${err.message}`);
      throw err;
    });
};

FeatureRequestSchema.statics.getAutoGenerated = function() {
  const cacheKey = 'getAutoGenerated';
  const cachedData = featureRequestCache.get(cacheKey);
  if (cachedData) return Promise.resolve(cachedData);
  return retryOperation(() => this.find({ autoGenerated: true }).sort({ submittedAt: -1 }))
    .then(data => { featureRequestCache.set(cacheKey, data); return data; })
    .catch(err => {
      logger.error(`Error fetching auto-generated feature requests: ${err.message}`);
      throw err;
    });
};

/**
 * Pre-validate: compute a stable content fingerprint over normalized
 * {title, description, category}. Drives the unique sparse index.
 */
FeatureRequestSchema.pre('validate', function(next) {
  try {
    if (this.title && this.description && this.category) {
      const payload = {
        t: String(this.title).trim().toLowerCase(),
        d: String(this.description).trim().toLowerCase(),
        c: this.category
      };
      this.contentFingerprint = crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');
    }
    next();
  } catch (err) {
    logger.error(`FeatureRequest pre-validate fingerprint error: ${err.message}`);
    next(err);
  }
});

/**
 * Idempotent create-or-get by content fingerprint. Uses findOneAndUpdate with
 * $setOnInsert + unique index for race-safe single-doc creation.
 */
FeatureRequestSchema.statics.upsertByFingerprint = async function(params = {}) {
  const { title, description, category, ...rest } = params;
  if (!title || !description || !category) {
    const error = new Error('title, description, and category are required for upsertByFingerprint');
    logger.error(`upsertByFingerprint validation error: ${error.message}`);
    throw error;
  }
  const fingerprintPayload = {
    t: String(title).trim().toLowerCase(),
    d: String(description).trim().toLowerCase(),
    c: category
  };
  const contentFingerprint = crypto.createHash('sha256').update(JSON.stringify(fingerprintPayload)).digest('hex');
  const payload = { title, description, category, ...rest, contentFingerprint };

  try {
    const doc = await retryOperation(
      () => this.findOneAndUpdate(
        { contentFingerprint },
        { $setOnInsert: payload },
        { new: true, upsert: true }
      ),
      { retries: 3 }
    );
    try { featureRequestCache.flushAll(); } catch (e) {
      logger.warn(`FeatureRequest cache flush warning on upsertByFingerprint: ${e.message}`);
    }
    return doc;
  } catch (err) {
    if (err && err.code === 11000) {
      logger.warn(`Duplicate fingerprint detected, returning existing document. fingerprint=${contentFingerprint}`);
      const existing = await retryOperation(() => this.findOne({ contentFingerprint }), { retries: 3 });
      if (existing) return existing;
    }
    logger.error(`upsertByFingerprint error: ${err.message}`);
    throw err;
  }
};

export const FeatureRequest = mongoose.model('FeatureRequest', FeatureRequestSchema);
