/**
 * CloudFront's error page reached a link checker as a success on the full tier (TMZ, 2026-10-09).
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { isUnusableResult, stubEvidence } from '../../src/api/external/routes/scraping.js';

const html = '<html><head><title>ERROR: The request could not be satisfied</title></head><body>' + ' '.repeat(9000) + '</body></html>';
const page = (title, text) => ({ success: true, _rawHtml: html, content: { title, text } });

test('the CloudFront 403 page is a block, with high confidence', () => {
  const r = page('ERROR: The request could not be satisfied',
    '403 ERROR The request could not be satisfied. Request blocked. We can\'t connect to the server for this app or website at this time. Generated by cloudfront (CloudFront) Request ID: abc');
  assert.equal(isUnusableResult(r), true);
  assert.equal(stubEvidence(r).detector, 'challenge-marker');
});

test('a long article that mentions the phrase is not', () => {
  const text = 'An article about CDNs. The request could not be satisfied, the error said. ' + 'Real reporting. '.repeat(400);
  assert.equal(isUnusableResult({ success: true, _rawHtml: html + text, content: { title: 'CDN outage explained', text } }), false);
});
